org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true

# Build optimization
android.enableBuildCache=true
android.enableDexingArtifactTransform=true
android.enableExternalNativeBuildCache=true
android.enableParallelJsonGen=true
android.enableAapt2Jni=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.workers.max=8

# Skip unused resources
android.useMinimalKeepRules=true
android.enableShrinkResourcesInRelease=true
