name: Flutter Production CI

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  FLUTTER_VERSION: "3.22.x"
  APP_PATH: mobile

on:
  push:
    branches: [main]
  workflow_dispatch:
  release:
    types: [created]

jobs:

  android-build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Cache Flutter Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}

      - name: Install Flutter Packages
        run: |
          cd $APP_PATH
          flutter pub get

      - name: Run Flutter Analyzer
        run: |
          cd $APP_PATH
          flutter analyze

      - name: Run Unit Tests
        run: |
          cd $APP_PATH
          flutter test

      - name: Build APK
        run: |
          cd $APP_PATH
          flutter build apk --release

      - name: Build App Bundle
        run: |
          cd $APP_PATH
          flutter build appbundle --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: mobile/build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: mobile/build/app/outputs/bundle/release/app-release.aab



  ios-build:
    name: iOS Build
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Cache Flutter Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: macos-pub-${{ hashFiles('**/pubspec.lock') }}

      - name: Install Dependencies
        run: |
          cd $APP_PATH
          flutter pub get

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd $APP_PATH/ios
          pod repo update
          pod install

      - name: Build iOS
        run: |
          cd $APP_PATH
          flutter build ios --release --no-codesign

      - name: Upload iOS Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: mobile/build/ios



  release:
    name: Create GitHub Release Artifacts
    needs: [android-build, ios-build]
    runs-on: ubuntu-latest

    if: github.event_name == 'release'

    steps:
      - name: Download Android APK
        uses: actions/download-artifact@v4
        with:
          name: android-apk

      - name: Download Android AAB
        uses: actions/download-artifact@v4
        with:
          name: android-aab

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app-release.apk
            app-release.aab
