name: Flutter Mobile Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  android-build:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.x"

      - name: Install dependencies
        run: |
          cd mobile
          flutter pub get

      - name: Build APK
        run: |
          cd mobile
          flutter build apk --release

      - name: Build App Bundle
        run: |
          cd mobile
          flutter build appbundle --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: mobile/build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: mobile/build/app/outputs/bundle/release/app-release.aab


  ios-build:
    name: Build iOS
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.x"

      - name: Install dependencies
        run: |
          cd mobile
          flutter pub get

      - name: Install CocoaPods
        run: |
          cd mobile/ios
          pod install

      - name: Build iOS
        run: |
          cd mobile
          flutter build ios --release --no-codesign

      - name: Package IPA
        run: |
          cd mobile
          mkdir -p build/ios/ipa
          xcodebuild -workspace ios/Runner.xcworkspace \
          -scheme Runner \
          -configuration Release \
          -sdk iphoneos \
          -archivePath build/ios/archive/Runner.xcarchive archive

      - name: Upload iOS build
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: mobile/build/ios
